spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: foo
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
logging:
  level:
    com.cardinalsolutions: DEBUG
    org.springframework.security: DEBUG
