spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: scott
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
logging:
  level:
    com.cardinalsolutions: DEBUG
    org.springframework.security: DEBUG
---    
spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
logging:
  level:
    com.cardinalsolutions: DEBUG
    org.springframework.security: DEBUG