kind: BuildConfig
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: spring-boot-demo
  name: spring-boot-demo
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: spring-boot-demo:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.2
        namespace: openshift
    type: Source