apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "conference-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://smorgan@gitlab.cardinalsolutions.com/smorgan/ConferenceSpeakers.git"
      sourceSecret:
        name: "gitlabcreds"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipeline.groovy
kind: List
metadata: []