apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: conferencepipeline
    name: conferencepipeline
  name: conferencepipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://smorgan@gitlab.cardinalsolutions.com/smorgan/ConferenceSpeakers.git
      ref: master
    sourceSecret: gitlabcreds
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: pipeline.groovy
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
